# Fly.io configuration for Dreamina API Server
app = "dreamina-api"
primary_region = "sin"  # Singapore - change to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  FLASK_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/"

[[vm]]
  size = "shared-cpu-1x"
  memory = "2gb"
  swap_size_mb = 512
