services:
  - type: web
    name: dreamina-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8080
